### ISSUE TITLE
Error tras ejecutar el .phar

### ISSUE THREAD

**Issue by SNepo** [sysPass/syspass-decrypter#1]
Buenas tras lanzar la linea del phar. La version de php que tengo es la 7.3 y el xml esta sacado de un syspass 1-2-beta

La linea que uso es esta.

php syspass-decrypter.phar spd:search-account --xmlpath ./syspass.xml

Me arroja este error:

 [error] #0 phar:///root/syspass-decrypter.phar/lib/SPDecrypter/Services/XmlReader/XmlParser.php(83): SPDecrypter\Services\XmlReader\XmlChecker::validateSchema(Object(DOMDocument))
#1 phar:///root/syspass-decrypter.phar/lib/SPDecrypter/Commands/SearchAccountCommand.php(119): SPDecrypter\Services\XmlReader\XmlParser->initialize('./syspass.xml', Object(SPDecrypter\Services\XmlReader\XmlReader), 'Darwin', NULL)
#2 phar:///root/syspass-decrypter.phar/vendor/symfony/console/Command/Command.php(255): SPDecrypter\Commands\SearchAccountCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///root/syspass-decrypter.phar/vendor/symfony/console/Application.php(921): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///root/syspass-decrypter.phar/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(SPDecrypter\Commands\SearchAccountCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///root/syspass-decrypter.phar/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///root/syspass-decrypter.phar/lib/SPDecrypter/bootstrap.php(48): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///root/syspass-decrypter.phar/cli.php(27): require('phar:///root/sy...')
#8 /root/syspass-decrypter.phar(14): require('phar:///root/sy...')
#9 {main}
[error] Invalid XML schema

¿Puede ser porque no es compatible por xml o me falta alguna dependencia?

**Comment by nuxsmin** [comment]
Buenas, el error es debido  a que el esquema XML no es compatible, ya que la versión debe de ser 3.0 o superior. 

Saludos!

**Comment by SNepo** [comment]
Me lo temia, ahora lo que tendre que abrir otro isue en el normal para ver porque no actualiza.

Muchas gracias y un saludo.
