### ISSUE TITLE
CSV output

### ISSUE THREAD

**Issue by matejzero** [sysPass/syspass-decrypter#3]
Hello,

we export passwords in cleartext, print them and save them in the vault in case our syspass app and USB backups are somehow destroyed / unavailable.

I tried using the output of the script, but it turns out we have some really wide fields (think long descriptions in notes / urls. Would it be possible to get an option to print the output to a CSV file? In that case, Excel can take care of formating and output is more readable. It also gives us an option to sort accounts.

Thanks!

**Comment by nuxsmin** [comment]
Hello, such feature has been discussed for a time ago and my opinion is that CSV files are insecure so I'm not willing to perform such kind of export from a security application. Anyway, it could be easily done with some programming knowledge.

I did provide this utility to keep the security "chain" so exporting to a plaintext CSV would break it.

Regards.
